In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np

In [2]:
import pandas as pd
import numpy as np
from pandas import Series, DataFrame
import Bio
from Bio import SeqIO,AlignIO
from sklearn.feature_extraction.text import CountVectorizer

In [3]:
def get_kmer_table(genes,gene_len):
    
    count_vect = CountVectorizer(analyzer='char',ngram_range=(2,5))
    X = count_vect.fit_transform(genes)
    chars = count_vect.get_feature_names()
    chars
    kmers = X.toarray()
    kmer_freq = []
    for i in range(len(genes)):
        kmer_freq.append(kmers[i]/gene_len[i])
    input = pd.DataFrame(kmer_freq,columns=chars)
    return input

def get_ids(filename):
    ids = []
    for record in SeqIO.parse(filename, "fasta"):
        ids.append(record.id)

def get_gene_sequences(filename):
    genes = []
    for record in SeqIO.parse(filename, "fasta"):
        genes.append(str(record.seq))
    return genes

# genes: a list of gene sequences, which can directly be generated from get_gene_sequences().
def get_gene_len(genes):
    gene_len = []
    
    for i in range(len(genes)):
        gene_len.append(len(genes[i]))
    return gene_len

In [4]:
genes_0 = get_gene_sequences("label0.fasta")
genes_1 = get_gene_sequences("label1.fasta")
gene_len_0 = get_gene_len(genes_0)
gene_len_1 = get_gene_len(genes_1)
all_genes = genes_0 + genes_1
all_gene_len = gene_len_0 + gene_len_1
kmer_table = get_kmer_table(all_genes,all_gene_len)
kmer_table

aa       aaa      aaaa     aaaaa     aaaac     aaaag     aaaat  \
0    0.077253  0.024594  0.007960  0.002347  0.001735  0.001735  0.002143   
1    0.029176  0.005106  0.000486  0.000000  0.000243  0.000000  0.000243   
2    0.068164  0.016962  0.004241  0.001649  0.001021  0.000707  0.000785   
3    0.074582  0.023697  0.004989  0.000748  0.001746  0.000748  0.001746   
4    0.087324  0.024485  0.007151  0.001517  0.001733  0.002384  0.001517   
..        ...       ...       ...       ...       ...       ...       ...   
352  0.072492  0.018723  0.005349  0.002400  0.001029  0.000892  0.000960   
353  0.086561  0.021344  0.005534  0.001186  0.001976  0.001186  0.001186   
354  0.074803  0.018275  0.005111  0.001084  0.001704  0.000929  0.001394   
355  0.077117  0.017770  0.004694  0.001509  0.001509  0.000671  0.001006   
356  0.102380  0.030294  0.009198  0.002500  0.002400  0.001200  0.003099   

         aaac     aaaca     aaacc  ...  ysc  yscc  ysccg   yt  ytc  ytca  \
0    0.005409  0.001531  0.000918  ...  0.0   0.0    0.0  0.0  0.0   0.0   
1    0.001702  0.000243  0.000243  ...  0.0   0.0    0.0  0.0  0.0   0.0   
2    0.004476  0.000628  0.001492  ...  0.0   0.0    0.0  0.0  0.0   0.0   
3    0.004989  0.001247  0.000499  ...  0.0   0.0    0.0  0.0  0.0   0.0   
4    0.006284  0.001083  0.001300  ...  0.0   0.0    0.0  0.0  0.0   0.0   
..        ...       ...       ...  ...  ...   ...    ...  ...  ...   ...   
352  0.004321  0.001372  0.001234  ...  0.0   0.0    0.0  0.0  0.0   0.0   
353  0.004743  0.001581  0.001186  ...  0.0   0.0    0.0  0.0  0.0   0.0   
354  0.004336  0.001704  0.001084  ...  0.0   0.0    0.0  0.0  0.0   0.0   
355  0.005197  0.002012  0.001509  ...  0.0   0.0    0.0  0.0  0.0   0.0   
356  0.006799  0.002000  0.001300  ...  0.0   0.0    0.0  0.0  0.0   0.0   

     ytcag  ytt  ytta  yttac  
0      0.0  0.0   0.0    0.0  
1      0.0  0.0   0.0    0.0  
2      0.0  0.0   0.0    0.0  
3      0.0  0.0   0.0    0.0  
4      0.0  0.0   0.0    0.0  
..     ...  ...   ...    ...  
352    0.0  0.0   0.0    0.0  
353    0.0  0.0   0.0    0.0  
354    0.0  0.0   0.0    0.0  
355    0.0  0.0   0.0    0.0  
356    0.0  0.0   0.0    0.0  

[357 rows x 1830 columns]

In [7]:
from sklearn.mixture import GaussianMixture as GMM
gmm = GMM(n_components=2).fit(kmer_table)
labels = gmm.predict(kmer_table)

In [9]:
labels

array([0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,

In [10]:
probs = gmm.predict_proba(kmer_table)
print(probs)

[[1.00000000e+000 7.45642781e-037]
 [1.70563791e-126 1.00000000e+000]
 [1.64327865e-027 1.00000000e+000]
 [1.00000000e+000 6.57937775e-101]
 [1.00000000e+000 7.31551918e-076]
 [1.00000000e+000 0.00000000e+000]
 [5.25837317e-267 1.00000000e+000]
 [1.11636756e-316 1.00000000e+000]
 [2.23073406e-187 1.00000000e+000]
 [5.40000426e-018 1.00000000e+000]
 [6.25337710e-132 1.00000000e+000]
 [1.00000000e+000 1.01594690e-073]
 [1.02895589e-044 1.00000000e+000]
 [4.29076662e-115 1.00000000e+000]
 [1.00000000e+000 2.38017061e-203]
 [1.00000000e+000 9.07143026e-162]
 [9.46739804e-230 1.00000000e+000]
 [1.09438896e-243 1.00000000e+000]
 [1.00000000e+000 0.00000000e+000]
 [1.00000000e+000 0.00000000e+000]
 [1.00000000e+000 1.04593697e-318]
 [5.76165097e-110 1.00000000e+000]
 [1.00000000e+000 1.83693062e-046]
 [5.87323614e-111 1.00000000e+000]
 [7.71541920e-094 1.00000000e+000]
 [1.29614814e-125 1.00000000e+000]
 [0.00000000e+000 1.00000000e+000]
 [4.87121872e-087 1.00000000e+000]
 [6.72786272e-122 1.

In [14]:
gmm1 = GMM(n_components=2,covariance_type="spherical").fit(kmer_table)
labels1 = gmm1.predict(kmer_table)
labels1

array([0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,

In [15]:
gmm2 = GMM(n_components=2,covariance_type="full").fit(kmer_table)
labels2 = gmm2.predict(kmer_table)
labels2

array([1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,

In [16]:
gmm3 = GMM(n_components=2,covariance_type="tied").fit(kmer_table)
labels3 = gmm3.predict(kmer_table)
labels3

array([1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,